spring:
  profiles:
    active: dev
#远程调试工具配置
  devtools:
    remote:
#      secret: hisuap
      secret: mysecret
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  application:
    name: calltape
  #文件上传下载大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
    algorithm: PBEWithMD5AndDES
